on: [push]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      run: |
        echo `python3 --version`
        sudo apt-get install -y python-setuptools
        sudo apt-get install -y python3-sphinx
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools
      id: build
    - name: Build the docset
      run: |
        cd docs/
        pip install -r requirements.txt
        make html
    - name: Get output time
      run: echo "The time was ${{ steps.build.outputs.time }}"      
    - name: Upload docs preview
        uses: seemethere/upload-artifact-s3@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
          retention-days: 14
          s3-bucket: doc-previews
          if-no-files-found: error
          path: docs
          s3-prefix: pytorch/executorch/${{ github.event.pull_request.number }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/html # The folder the action should deploy. 
